// AUTO-GENERATED by scripts/sync-images.mjs — do not edit by hand.
// Re-run "node scripts/sync-images.mjs" after adding new photos to the
// "NPGC WEBSITE" folder to refresh this file.

export type GalleryCategory =
  | "pastor"
  | "worship"
  | "prayer"
  | "congregation"
  | "special-events"
  | "children"
  | "choir"
  | "outreach";

export type GalleryImage = {
  src: string;
  category: GalleryCategory;
};

export const galleryImages: GalleryImage[] = [
  {
    "src": "/images/gallery/special-events/img-20250417-wa0043.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0044.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0045.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0046.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0047.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0049.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0051.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0052.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0053.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0054.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0055.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0056.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0057.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0058.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0059.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0060.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0061.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0062.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/pastor/img-8279-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8286-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8287-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6181.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6214.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6375.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6413.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6415.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6440.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8148-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8157-20251005.png",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8186-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8425-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8461-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8482-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8505-20251005.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/worship/13-7img-4140.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-4176.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-4315.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-4977-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-4985-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-4990-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5143-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5154-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5186-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5187-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5211-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5253.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5259.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5300.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5301.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5384-1.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5384.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5464.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5586-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5591-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5619-2.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7p1081419.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7p1081440.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9737.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9744.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9778.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9779.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9787.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/prayer/2109img-7273.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7304.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7334.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7350.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7359.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7419.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7461.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7469.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/2109img-7476.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/congregation/img-8740-20251012.jpg",
    "category": "congregation"
  },
  {
    "src": "/images/gallery/congregation/img-8746-20251012.jpg",
    "category": "congregation"
  },
  {
    "src": "/images/gallery/congregation/img-8747-20251012.jpg",
    "category": "congregation"
  },
  {
    "src": "/images/gallery/congregation/p1098271-20251012.jpg",
    "category": "congregation"
  },
  {
    "src": "/images/gallery/congregation/p1098294-20251012.jpg",
    "category": "congregation"
  },
  {
    "src": "/images/gallery/congregation/p1098320-20251012.jpg",
    "category": "congregation"
  },
  {
    "src": "/images/gallery/congregation/p1098335-20251012.jpg",
    "category": "congregation"
  }
];

export function imagesByCategory(category: GalleryCategory): GalleryImage[] {
  return galleryImages.filter((img) => img.category === category);
}
