// AUTO-GENERATED by scripts/sync-images.mjs — do not edit by hand.
// Re-run "node scripts/sync-images.mjs" after adding new photos to a
// client-provided "ALL PHOTOS TYPES" folder inside public/ to refresh this file.

export type GalleryCategory =
  | "welcome"
  | "happy"
  | "prayer"
  | "ministration"
  | "pastor"
  | "pastors-wife"
  | "programs"
  | "testimonies"
  | "worship"
  | "special-events";

export type GalleryImage = {
  src: string;
  category: GalleryCategory;
};

export const galleryImages: GalleryImage[] = [
  {
    "src": "/images/gallery/welcome/img-0189-enhanced-nr-20260719.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/img-6181-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1098214-20251012-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1098271-20251012-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1098320-20251012-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1098335-20251012-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138892-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138893-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138895-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138899-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138902-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138903-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138909-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138911-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138918-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138921-enhanced-nr-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138923-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138949-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138952-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138959-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138972-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138977-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138977-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138982-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138988-enhanced-nr-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138990-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138992-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1138998-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1139000-20260712.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1139010-20260706.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1150518-20260726.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1150519-20260726.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1098348-20251012-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/welcome/p1098351-20251012-scaled.jpg",
    "category": "welcome"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0043.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0044.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0045.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0046.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0047.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0049.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0051.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0052.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0053.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0054.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0055.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0056.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0057.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0058.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0059.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0060.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0061.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/special-events/img-20250417-wa0062.jpg",
    "category": "special-events"
  },
  {
    "src": "/images/gallery/happy/13-7p1081419-scaled.jpg",
    "category": "happy"
  },
  {
    "src": "/images/gallery/happy/13-7p1081440-scaled.jpg",
    "category": "happy"
  },
  {
    "src": "/images/gallery/happy/img-8521-20251005-scaled.jpg",
    "category": "happy"
  },
  {
    "src": "/images/gallery/happy/img-8759-20251012-scaled.jpg",
    "category": "happy"
  },
  {
    "src": "/images/gallery/happy/img-9622-20251026-scaled.jpg",
    "category": "happy"
  },
  {
    "src": "/images/gallery/prayer/2109img-7460-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9665-20260705.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9787-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9791-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/13-7img-5039-2-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/13-7img-5569-2-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/13-7img-5579-2-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/13-7img-5582-2-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-0326-enhanced-nr-20260719.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-0363-enhanced-nr-20260719.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-3689-20260104-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-6283-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-6290-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-6295-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-6310-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-8170-20251005-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-8286-20251005-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-8287-20251005-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9061-20251019-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9758-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9776-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9785-scaled.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9853-20260712.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/prayer/img-9872-20260712.jpg",
    "category": "prayer"
  },
  {
    "src": "/images/gallery/ministration/13-7img-5783-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/13-7img-5832-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-8815-20251012-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-8824-20251012-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-8825-20251012-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-8830-20251012-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-8831-20251012-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-8836-20251012-scaled.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-9290-20251019-scaled-1.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-9527-enhanced-nr-20260705.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-9533-enhanced-nr-20260705.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-9534-20260705.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/ministration/img-9536-20260705.jpg",
    "category": "ministration"
  },
  {
    "src": "/images/gallery/pastor/13-7img-4176-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-4315-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5186-2-scaled-1.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5186-2-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5187-2-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5301-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5336-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5861-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/13-7img-5891-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/2109img-7469-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-0094-enhanced-nr-20260712.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-3887-20260104-1-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-4512-2-20260118-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-4663-20260118-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-6415-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastor/img-8461-20251005-scaled.jpg",
    "category": "pastor"
  },
  {
    "src": "/images/gallery/pastors-wife/13-7img-5960-scaled.jpg",
    "category": "pastors-wife"
  },
  {
    "src": "/images/gallery/pastors-wife/13-7img-5961-scaled.jpg",
    "category": "pastors-wife"
  },
  {
    "src": "/images/gallery/pastors-wife/13-7img-5962-scaled.jpg",
    "category": "pastors-wife"
  },
  {
    "src": "/images/gallery/pastors-wife/13-7img-5963-scaled.jpg",
    "category": "pastors-wife"
  },
  {
    "src": "/images/gallery/pastors-wife/img-8279-20251005-scaled.jpg",
    "category": "pastors-wife"
  },
  {
    "src": "/images/gallery/pastors-wife/img-8926-scaled.jpg",
    "category": "pastors-wife"
  },
  {
    "src": "/images/gallery/programs/486413983-18060219761044343-5792407174184104939-n.jpg",
    "category": "programs"
  },
  {
    "src": "/images/gallery/programs/489041454-18061555856044343-2359327884408875482-n.jpg",
    "category": "programs"
  },
  {
    "src": "/images/gallery/programs/489908129-18061430192044343-436248819539506981-n.jpg",
    "category": "programs"
  },
  {
    "src": "/images/gallery/programs/504464826-18066717989044343-2556750683563333193-n.jpg",
    "category": "programs"
  },
  {
    "src": "/images/gallery/programs/527870165-1109386184626845-287761674069718932-n-1.jpg",
    "category": "programs"
  },
  {
    "src": "/images/gallery/testimonies/13-7img-5539-2-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/13-7img-5591-2-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/2109img-7334-1-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/2109img-7334-scaled-1.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/2109img-7350-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/2109img-7359-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-0306-enhanced-nr-20260719.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-0710-20260726-1.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-0710-20260726.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-0711-20260726.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-0722-20260726.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-8747-20251012-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-8981-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/testimonies/img-8983-scaled.jpg",
    "category": "testimonies"
  },
  {
    "src": "/images/gallery/worship/13-7img-5538-2-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5551-2-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5598-2-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5619-2-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5637-2-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/13-7img-5655-2-1-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-0498-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-0500-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-0592-20260726.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-0620-20260726.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-3696-20260104-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-3697-20260104-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-4433-2-20260118-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-8176-20251005-1-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-8989-20251019-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9511-20251026-scaled.jpg",
    "category": "worship"
  },
  {
    "src": "/images/gallery/worship/img-9540-20251026-scaled.jpg",
    "category": "worship"
  }
];

export function imagesByCategory(category: GalleryCategory): GalleryImage[] {
  return galleryImages.filter((img) => img.category === category);
}
