// Moves photos from the client-organized "ALL PHOTOS TYPES" folder (dropped
// directly into public/) into public/images/gallery/<category>/, using the
// client's own folder names as the source of truth for categorization, then
// regenerates the gallery manifest consumed by the site.
//
// Re-run any time new images are added to "ALL PHOTOS TYPES":
//   node scripts/sync-images.mjs
//
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const sourceRoot = path.join(repoRoot, "public", "ALL PHOTOS TYPES");
const destRoot = path.join(repoRoot, "public", "images", "gallery");

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

// Client's folder name -> our gallery category slug. Folders not listed here
// are skipped (with a warning) rather than guessed at.
const FOLDER_TO_CATEGORY = {
  Entrances: "welcome",
  Welcome: "welcome",
  Happy: "happy",
  "Laying of hands by Pastor": "prayer",
  "Listening to Ministration": "ministration",
  Pastor: "pastor",
  "Pastor's wife": "pastors-wife",
  Prayer: "prayer",
  Programs: "programs",
  Testimonies: "testimonies",
  Worship: "worship",
  "Beyond Borders": "special-events",
};

function slugify(basename) {
  return basename
    .toLowerCase()
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function collectImages(dir) {
  const files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...collectImages(full));
    } else if (IMAGE_EXT.has(path.extname(entry.name).toLowerCase())) {
      files.push(full);
    }
  }
  return files;
}

if (!fs.existsSync(sourceRoot)) {
  console.log(`No "ALL PHOTOS TYPES" folder found at ${sourceRoot} — nothing to sync.`);
  process.exit(0);
}

fs.mkdirSync(destRoot, { recursive: true });

/** @type {Record<string, {src: string, category: string}[]>} */
const byCategory = {};
let moved = 0;
const seenDestNames = new Set();

for (const topEntry of fs.readdirSync(sourceRoot, { withFileTypes: true })) {
  if (!topEntry.isDirectory()) continue;
  const topDir = path.join(sourceRoot, topEntry.name);

  // "Events/Beyond Borders" is nested one level deeper than the rest.
  const subDirs = fs.readdirSync(topDir, { withFileTypes: true }).filter((e) => e.isDirectory());
  const foldersToScan = subDirs.length
    ? subDirs.map((d) => ({ name: d.name, dir: path.join(topDir, d.name) }))
    : [{ name: topEntry.name, dir: topDir }];

  for (const { name, dir } of foldersToScan) {
    const category = FOLDER_TO_CATEGORY[name];
    if (!category) {
      console.warn(`Skipping unmapped folder: ${name}`);
      continue;
    }
    const destDir = path.join(destRoot, category);
    fs.mkdirSync(destDir, { recursive: true });

    for (const file of collectImages(dir)) {
      const ext = path.extname(file).toLowerCase();
      let destName = `${slugify(path.basename(file))}${ext}`;
      let destPath = path.join(destDir, destName);
      const key = `${category}/${destName}`;
      if (seenDestNames.has(key)) {
        destName = `${slugify(path.basename(file))}-${moved}${ext}`;
        destPath = path.join(destDir, destName);
      }
      seenDestNames.add(`${category}/${destName}`);

      fs.copyFileSync(file, destPath);
      fs.rmSync(file);
      moved++;

      byCategory[category] ??= [];
      byCategory[category].push({ src: `/images/gallery/${category}/${destName}`, category });
    }
  }
}

// Clean up now-empty source tree.
function removeEmptyDirs(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) removeEmptyDirs(path.join(dir, entry.name));
  }
  if (fs.readdirSync(dir).length === 0) fs.rmdirSync(dir);
}
removeEmptyDirs(sourceRoot);

const manifestPath = path.join(repoRoot, "src", "lib", "gallery-manifest.ts");
const allImages = Object.values(byCategory).flat();

const fileContents = `// AUTO-GENERATED by scripts/sync-images.mjs — do not edit by hand.
// Re-run "node scripts/sync-images.mjs" after adding new photos to a
// client-provided "ALL PHOTOS TYPES" folder inside public/ to refresh this file.

export type GalleryCategory =
  | "welcome"
  | "happy"
  | "prayer"
  | "ministration"
  | "pastor"
  | "pastors-wife"
  | "programs"
  | "testimonies"
  | "worship"
  | "special-events";

export type GalleryImage = {
  src: string;
  category: GalleryCategory;
};

export const galleryImages: GalleryImage[] = ${JSON.stringify(allImages, null, 2)};

export function imagesByCategory(category: GalleryCategory): GalleryImage[] {
  return galleryImages.filter((img) => img.category === category);
}
`;

fs.writeFileSync(manifestPath, fileContents);

console.log(`Moved ${moved} images across ${Object.keys(byCategory).length} categories.`);
for (const [cat, imgs] of Object.entries(byCategory)) {
  console.log(`  ${cat}: ${imgs.length}`);
}
console.log(`Manifest written to src/lib/gallery-manifest.ts`);
