// Scans the parent "NPGC WEBSITE" folder for photos dropped there (root + any
// subfolders, e.g. "Photos", or new folders the client adds later), copies
// them into public/images/gallery/<category>/, and regenerates the gallery
// manifest consumed by the site. Re-run any time new images are added:
//
//   node scripts/sync-images.mjs
//
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const sourceRoot = path.resolve(repoRoot, ".."); // "NPGC WEBSITE" folder
const destRoot = path.join(repoRoot, "public", "images", "gallery");
const brandDestDir = path.join(repoRoot, "public", "brand");

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);
const SKIP_DIRS = new Set(["NPGC-CLAUDE", "node_modules", ".git"]);

/** @type {{ test: RegExp; category: string }[]} */
const rules = [
  { test: /^IMG-20250417-WA00/i, category: "special-events" },
  { test: /^13-7(IMG|P108)/i, category: "worship" },
  { test: /^2109IMG/i, category: "prayer" },
  { test: /^IMG_6\d{3}\./i, category: "pastor" },
  { test: /^IMG_8\d{3}-20251005/i, category: "pastor" },
  { test: /^IMG_8\d{3}-20251012/i, category: "congregation" },
  { test: /^IMG_9\d{3}\./i, category: "worship" },
  { test: /^P1098\d{3}-20251012/i, category: "congregation" },
];

function categoryFor(filename) {
  const rule = rules.find((r) => r.test.test(filename));
  return rule?.category ?? "congregation";
}

function walk(dir, files = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      walk(path.join(dir, entry.name), files);
    } else {
      files.push(path.join(dir, entry.name));
    }
  }
  return files;
}

function slugify(basename) {
  return basename
    .toLowerCase()
    .replace(/\.[^.]+$/, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const allFiles = walk(sourceRoot);
const seenBasenames = new Set();
/** @type {Record<string, {src: string, category: string}[]>} */
const byCategory = {};

fs.mkdirSync(destRoot, { recursive: true });
fs.mkdirSync(brandDestDir, { recursive: true });

// Logo: prefer the larger of the two known logo files.
const logoCandidates = allFiles.filter((f) => /logo/i.test(path.basename(f)));
if (logoCandidates.length) {
  const best = logoCandidates
    .map((f) => ({ f, size: fs.statSync(f).size }))
    .sort((a, b) => b.size - a.size)[0].f;
  fs.copyFileSync(best, path.join(brandDestDir, "npgc-logo.png"));
  console.log(`Logo -> public/brand/npgc-logo.png (from ${path.basename(best)})`);
}

let copied = 0;
for (const file of allFiles) {
  const basename = path.basename(file);
  const ext = path.extname(file).toLowerCase();
  if (!IMAGE_EXT.has(ext)) continue;
  if (/logo/i.test(basename) || /channels4_profile/i.test(basename)) continue;
  if (seenBasenames.has(basename)) continue; // dedupe (same photo saved in two folders)
  seenBasenames.add(basename);

  const category = categoryFor(basename);
  const destDir = path.join(destRoot, category);
  fs.mkdirSync(destDir, { recursive: true });
  const destName = `${slugify(basename)}${ext}`;
  fs.copyFileSync(file, path.join(destDir, destName));

  byCategory[category] ??= [];
  byCategory[category].push({ src: `/images/gallery/${category}/${destName}`, category });
  copied++;
}

const manifestPath = path.join(repoRoot, "src", "lib", "gallery-manifest.ts");
const allImages = Object.values(byCategory).flat();

const fileContents = `// AUTO-GENERATED by scripts/sync-images.mjs — do not edit by hand.
// Re-run "node scripts/sync-images.mjs" after adding new photos to the
// "NPGC WEBSITE" folder to refresh this file.

export type GalleryCategory =
  | "pastor"
  | "worship"
  | "prayer"
  | "congregation"
  | "special-events"
  | "children"
  | "choir"
  | "outreach";

export type GalleryImage = {
  src: string;
  category: GalleryCategory;
};

export const galleryImages: GalleryImage[] = ${JSON.stringify(allImages, null, 2)};

export function imagesByCategory(category: GalleryCategory): GalleryImage[] {
  return galleryImages.filter((img) => img.category === category);
}
`;

fs.writeFileSync(manifestPath, fileContents);

console.log(`Copied ${copied} images across ${Object.keys(byCategory).length} categories.`);
for (const [cat, imgs] of Object.entries(byCategory)) {
  console.log(`  ${cat}: ${imgs.length}`);
}
console.log(`Manifest written to src/lib/gallery-manifest.ts`);
